version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: codepromptpro_app2
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./.streamlit:/app/.streamlit
    environment:
      - PYTHONUNBUFFERED=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}